default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: members-only_development

test:
  <<: *default
  database: members-only_test

production:
  <<: *default
  database: members-only_production
  username: members-only
  password: <%= ENV["MEMBERS-ONLY_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>